### ISSUE TITLE
Unwanted space added after footnote markers

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#1]
For example in pramanavarttikavrtti.pdf p.49, line 1400 pramanavarttikavrtti.tex
`शा\-स्त्रा\-\edlabel{pvv.1-1}\footnote{\label{pvv.1-1}  १ स्तुत्या\- पुण्योपचया\-त् ।} दा\-वविध्नेन`
There should be no space after the closing parenthesis of the footnote.

**Comment by ppasedach** [comment]
Line 3710 in the xml file also has these space appears also there. After removing the space at this place it disappears in the pdf.

**Comment by paddymcall** [comment]
Has to be fixed in markup.

**Comment by paddymcall** [comment]
Fixed mainly in https://github.com/sarit/SARIT-corpus/commit/b7f069f0e7b711ccd92159d3afa04ba5d9fdd8cf

Please file individual problems against https://github.com/sarit/SARIT-corpus.
