### ISSUE TITLE
move milestones into margin

### ISSUE THREAD

**Issue by paddymcall** [paddymcall/SARIT-pdf-conversions#10]
how could we show pb/lb-s etc in margin? we need a robust command for this.

**Comment by ppasedach** [comment]
Generally `\ledsidenote` looks fine for this, but fails in unnumbered text, such as headings. I wonder if there's a way we can make sure they always appear within numbered text?

**Comment by ppasedach** [comment]
Package \marginnote might be a good option, see attached example.
[marginnotetest.pdf](https://github.com/paddymcall/SARIT-pdf-conversions/files/152708/marginnotetest.pdf)
[marginnotetest.txt](https://github.com/paddymcall/SARIT-pdf-conversions/files/152710/marginnotetest.txt) (Ending changed from `.tex` to `.txt`.)
