### ISSUE TITLE
font for footnote number

### ISSUE THREAD

**Issue by paddymcall** [paddymcall/SARIT-pdf-conversions#11]
Currently, the footnote numbers (both in the text and in the footer) are set in the font of the main text. That is scaled, so they look to big. Is it possible to set them in the default roman font, or to set them as devanagari?

**Comment by ppasedach** [comment]
The following insertion to the preamble changes the formatting of the footnotes in text as well as footer to devanagari. There are still some font problems however, which make the compile take ages. This is not final yet, but it will give you some idea. I am here following p. 234 of the memoir manual, it seems reledmac doesn't get involved here, although I'm not certain about that.

```
\makeatletter
\renewcommand*{\@makefnmark}{\hbox{\textsuperscript{\addfontfeatures{Mapping=devanagarinumerals}\footnotesize \@thefnmark}}}
\makeatother
\footmarkstyle{\textsuperscript{\addfontfeatures{Mapping=devanagarinumerals}#1}}
```

Another possible road might be to add `Mapping=devanagarinumerals` to the `\newfontfamily\devanagarifont`, which would then change all the other numbering to devanagari too, such as the line numbers, chapter numbers etc..

You asked about the scaling, that should also be possible to adjust as an option to `\addfontfeatures`. I'll look into it later.

**Comment by paddymcall** [comment]
The problem is that Chandas has a bad ratio to the roman font. We have to scale it for legibility, but that also scales up the roman numerals (taken from Chandas in these cases).

Please evaluate if one of these fonts does not have the issue: https://packages.debian.org/squeeze/all/ttf-devanagari-fonts/filelist

**Comment by ppasedach** [comment]
I'm wondering, if, rather than scaling up the devanagari font only, using `12pt` as a class option to `memoir` wouldn't be the better way to give us better readability ? For an example see [pramanavarttikavrtti12pt.pdf](https://github.com/paddymcall/SARIT-pdf-conversions/files/144524/pramanavarttikavrtti12pt.pdf) (Using arabic numbers again.)

**Comment by paddymcall** [comment]
best to switch to another font, eventually; can't fix this at the moment for Chandas: having 12pt globally does not change the ratio of the devanagari letters to the arabic numerals in the Chandas font.
