### ISSUE TITLE
Use nonbreaking space before daṇḍas

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#13]
I wonder if it's possible, and desirable, using a search and replace in the xsl transformation, to replace some spaces, particularly the ones before  daṇḍas, and around verse numbers, by nonbreaking spaces, `~`. Compare the two sections  of sample output:

Without nonbreaking spaces:
![selection_061](https://cloud.githubusercontent.com/assets/11517856/13054931/9854dffc-d40c-11e5-96a7-b563e571b736.png)
With nonbreaking spaces:
![selection_063](https://cloud.githubusercontent.com/assets/11517856/13054936/9e2930d6-d40c-11e5-9b1c-a63bef6a5338.png)

```
      \begin{center}%% label @type='head'
    \textbf{ख. शा\-स्त्रा\-रम्भप्रयोजनम्}
    \end{center}


      \pstart श्रोतृदोषबा\-हुल्या\-च्छा\-स्त्रेण परोपका\-रमपश्यन् सू\-क्ता\-भ्या\-सभा\-वितचित्तता\-मेवा\-त्मनः शा\-स्त्रा\-रम्भका\-रणन्दर्शयन् वक्रोक्त्या\- दोषता\-पनयनेन शा\-स्त्रे श्रोतृन् प्रवर्तयितुम(ा\-) ह~।
    \pend


        \stanza
\edlabel{pvv.2-asterisk}\footnote{\label{pvv.2-asterisk}  * द्रष्टव्यं परिशिष्टं १।१-४} प्रा\-यः प्रा\-कृतसक्तिरप्रतिबलप्रज्ञो जनः केवलं,ना\-नर्थ्येव सुभा\-षितैः परिगता\- विद्वेष्ट्यपी\-र्ष्या\-मलैः ।&तेना\-यं न परोपका\-र इति नश्चिन्ता\-पि चेतस्ततः,सू\-क्ता\-भ्या\-सविबर्द्धितव्यसनमित्यत्रा\-नुबद्धस्पृहम्~॥~२~॥\&

```

**Comment by paddymcall** [comment]
This is an xml problem, one should use the appropriate spacing signs in the right places. (e.g., NON-BREAKING SPACE).

**Comment by paddymcall** [comment]
Will close only when fixed in the XML branch.

**Comment by ppasedach** [comment]
That would be just [a unicode character](http://www.fileformat.info/info/unicode/char/00a0/index.htm) in the running text, or would it be a tag? Is anything like that being used in SARIT already?

**Comment by paddymcall** [comment]
Please reopen if not solved.
