### ISSUE TITLE
Use of \color can affect things in the margin.

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#17]
Such as `reledmac`'s line numbers ([issue reported](https://github.com/maieul/ledmac/issues/504)) or marginnotes. See the following example from pramanavarttikavrtti.pdf, p.13: 
![auswahl_067](https://cloud.githubusercontent.com/assets/11517856/13427215/d4140f16-dfb2-11e5-9acf-9828a8a0cfa9.png)

**Comment by paddymcall** [comment]
For marginnotes, we can solve this in the XSLT (and also should solve it there).  For reledmac, I don't know.

**Comment by ppasedach** [comment]
`\renewcommand*{\numlabfont}{\normalfont\scriptsize\color{black}}` in the preamble solves it for reledmac.
