### ISSUE TITLE
! Package polyglossia Error: The current roman font does not contain the Devanagari script! in dharmottarapradiipa.tex 

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#19]
At `\printbibliography`.

**Comment by paddymcall** [comment]
This seems to be a bug caused by using biblatex and polyglossia together:

```
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage{sanskrit}
% english should be available, notes and stuff
\setotherlanguage{english}

\usepackage{fontspec}
% make sure English font is there
\newfontfamily\englishfont[Mapping=tex-text]{TeX Gyre Schola}
% set up a devanagari font
\newfontfamily\devanagarifont[Script=Devanagari]{Chandas}

\usepackage[backend=biber,%
% bibstyle=authoryear,%
language=english,% ignored?
sortlocale=en_US,%
]{biblatex}

%% this doesn't help
% \renewcommand\bibfont{\rmfamilylatin}
% \renewcommand\bibsetup{\selectlanguage{english}}

\addbibresource[location=remote]{https://raw.githubusercontent.com/paddymcall/Stylesheets/HEAD/profiles/sarit/latex/bib/sarit.bib}

\begin{document}

\cite{dp-edP}
मंगलं महा श्री ॥

\printshorthands
\printbibliography
\end{document}
```

Please propose a fix for that.

**Comment by paddymcall** [comment]
Specifically, it's in the treatment of the url of dp-edP (but the main problem is actually that the font of the whole bibliography is not switched to the font that polyglossia would use).

**Comment by ppasedach** [comment]
This bug has been fixed, see https://github.com/plk/biblatex/issues/385 . The "language" package option will now, using biblatex 3.4 (development branch), which requires biber 2.5, set the font of the bibliography items to the font used by that language. biblatex needs to be loaded with the options as follows: `\usepackage[language=english,autolang=langname]{biblatex}` The font for  the headings and the abbreviations is however not touched by that, these one needs to set by redefining them, as per the example here: https://github.com/plk/biblatex/issues/385#issuecomment-199744432 . The `url` field remains somewhat problematic, which can be done away with by \urlstyle{same} in the preamble, or one can see other options from the `url` package. 

I'll apply all this to our short example.

Or one could consider switching to English as the main language for the document, and keep only the main text in a Sanskrit environment.

**Comment by ppasedach** [comment]
One more thing to add: With the development version of `biblatex` one will also need the development version of `polyglossia`.
