### ISSUE TITLE
Where are labels defined for the internal references?

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#20]
The ones dealt with via commands like `\cref{ABC.1.2.3}`? The `\cite{abc123}` family of commands work together with `biber`, but `\cref` expects `\label`s to be defined inside the document. Where are they? Not yet implemented? Wouldn't they point to a primary literature reference, where we'd specify the edition used? Or are they even supposed to point to specific places in other files in SARIT? I see that pramanavarttikavrtti.tex has many `\label` commands, but dharmottarapradiipa.tex doesn't.

**Comment by paddymcall** [comment]
\label{} and \cref{} are for maintaining internal links (corresponding roughly to the xml:id attribute and the ref element.

\cite{} is for bibliographic references (which can also be internal). This is a bug then for    dharmottarapradiipa.tex.

**Comment by ppasedach** [comment]
That means that something like `\cref{Pā.4.3.59}` should rather be `\cite[4.3.59]{Pā.}`, and `Pā.` would need to be included, with further details, in the `.bib` file?

**Comment by paddymcall** [comment]
Those are canonical refs, set by the cRef attribute (has nothing to do with LaTeX's cleveref cref commands).  Should be handled correctly now, distinguishing cRef and target attributes.
