### ISSUE TITLE
Improve footnotes/critical apparatus

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#26]
At the moment we have footnote markers in the text, keyed to the footnotes numbered per page.

![selection_081](https://cloud.githubusercontent.com/assets/11517856/14101488/211ad798-f595-11e5-957d-1d8b1be88f1d.png)

The numbers (from the source edition) at the beginning of the footnotes should be moved from the text presumably into an attribute of the note tag. This would give us the possibility to either hide them, or display them with special formatting, possibly also at the end of the note. 

In order to remove the footnote numbers from the text, keying the notes to line numbers and using lemmata, we probably want to shift them to reledmac. Regarding that our biggest problem is that we have no beginning and end points for the lemmata, only one point, where we now have the footnote marker. One possible default lemma could be from the beginning of the word the note is attached to to its end. Is this default reasonable? Apart from that, however there will be cases in which a word (or rather string) might be too long, or two footnote markers are attached to one string, possibly also other problems, for which we would need human interaction to specifically mark beginning- and endpoints of the lemma, which would have to be done in the xml files, probably also, for reference, inserting a milestone  tag at the position of the source edition's footnote marker. The notes requiring human interaction will have to be identified by a well-tested search. 

I'll make a small example to see how that would look like.

**Comment by ppasedach** [comment]
Here [a sample](https://github.com/paddymcall/SARIT-pdf-conversions/files/193453/sample1.pdf) containing the beginning of pramanavarttikavrtti. The next page then begins with an asterisk instead of a number, not attached to any word, so this would be a case requiring human interaction.

**Comment by paddymcall** [comment]
This is now in the latest stylesheet version. But a few problems remain:

How to deal with paragraphs in reledmac notes? Especially: 
when can we use \par and \begin{verse}...\end{verse}? And a note in a note?

All of this is possible according to the TEI guidelines. It depends also, but not only, on arrangementX/Xarrangement of reledmac (using paragraph breaks a lot of things, but what about twocol or default settings?)

**Comment by ppasedach** [comment]
Here a MWE that shows what happens if you have an explicit linebreak in a critical footnote:

```
\documentclass{article}
\usepackage{reledmac}
\Xarrangement[A]{paragraph}

\begin{document}
\beginnumbering
\pstart
\edtext{something}{\Afootnote{else.}}. And now \edtext{something more}{\Afootnote{Something\\
with\\
some\\ linebreaks.}}
\pend
\endnumbering
\end{document}
```

![selection_082](https://cloud.githubusercontent.com/assets/11517856/14225324/4478b002-f8bf-11e5-8b8e-0e3dae8944c1.png)
Beautiful. Only the last line appears. The best of it is that you get no warning or error message! So we have to be very careful with this.

Doing some simple testing switching from \Xarrangement[A]{paragraph} to default or twocol works o.k.:
![selection_083](https://cloud.githubusercontent.com/assets/11517856/14225357/7f8d2cbc-f8c0-11e5-88d2-00f68147ea23.png)
![selection_084](https://cloud.githubusercontent.com/assets/11517856/14225360/949dbc02-f8c0-11e5-97ae-b4b83816147b.png)

If I put a `verse` environment around my lines I get similar results:

![selection_085](https://cloud.githubusercontent.com/assets/11517856/14225465/f643db8c-f8c3-11e5-9d81-1308c3ec8eca.png)
![selection_086](https://cloud.githubusercontent.com/assets/11517856/14225468/0d65e026-f8c4-11e5-8160-9282c2438370.png)
![selection_087](https://cloud.githubusercontent.com/assets/11517856/14225469/1da5f73c-f8c4-11e5-9c96-b417392c77b8.png)

A lemma that contains a second lemma (note: This is not exactly footnote in a footnote, but probably what you meant, is it?) is documented in the reledmac documentation and seems to work:

```
\documentclass{article}
\usepackage{reledmac}
\Xarrangement[A]{paragraph}

\begin{document}
\beginnumbering
\pstart
\edtext{something}{\Afootnote{else.}}. And now \edtext{something \edtext{more}{\Afootnote{Not so much more.}}}{\Afootnote{Something with some linebreaks.}} 
\pend
\endnumbering
\end{document}
```

![selection_088](https://cloud.githubusercontent.com/assets/11517856/14225545/5ffc933c-f8c6-11e5-85bc-ae15c5f87dac.png)

Or did you really mean footnote within footnote, for which one normally would use `\footnotemark` `\footnotetext`? 

```
\documentclass{article}
\usepackage{reledmac}
\Xarrangement[A]{paragraph}

\begin{document}
\beginnumbering
\pstart
\edtext{something}{\Afootnote{else.}}. And now \edtext{something more}{\Afootnote{Something with a footnote.\footnotemark}}\footnotetext{Test.} 
\pend
\endnumbering
\end{document}
```

![selection_089](https://cloud.githubusercontent.com/assets/11517856/14225567/985b4376-f8c7-11e5-92d0-7236cd57ab45.png)

The numbering is off. Would need to be investigated, but maybe it's not required anyways?

So it seems that linebreaks and verse environments work with reledmac, but not, or not easily, with the paragraphed mode. `twocol` looks like an easy option. I can also look at workarounds for `paragraph`. Later I'll have to check some real world examples and their handling.

**Comment by ppasedach** [comment]
The current maintainer of reledmac has [no idea](http://tex.stackexchange.com/questions/302106/line-breaks-in-paragraphed-footnotes-in-reledmac?noredirect=1#comment732402_302106) how to do the line breaks in paragraphed footnotes, so I'd say we go for the twocol option, at least for now. Still need to check if it doesn't break anything.

**Comment by paddymcall** [comment]
Indeed, it's unclear how one should format pars in an environment that tries to get rid of them.

**Comment by paddymcall** [comment]
As for the footnote markers, this is fixed in 
https://github.com/paddymcall/SARIT-corpus/commit/084f0d7ed05e70e475846ed93af44a01ae8790ea

The other things should be filed as feature requests, not bugs.
