### ISSUE TITLE
! No room for a new \skip

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#3]
xelatex hangs many times with similar messages. I suspect an incompatibility of eledmac with recent versions of latex, as I've seen before, and indeed as in those cases a 

```
\RequirePackage{etex}
\reserveinserts{40}
```

at the very beginning of the tex file fixes it. This should not be needed though.

**Comment by paddymcall** [comment]
please post a log file showing these problems, can't see them here.

**Comment by ppasedach** [comment]
It occurs to me only on my notebook (2GB RAM only), not on my desktop machine.

[pramanavarttikavrtti.log.txt](https://github.com/paddymcall/SARIT-pdf-conversions/files/118110/pramanavarttikavrtti.log.txt)

**Comment by paddymcall** [comment]
please check again with fix to paddymcall/SARIT-pdf-conversions/issues/4

**Comment by ppasedach** [comment]
This doesn't seem to fix it. Anyways, as it seems to primarily affect my notebook, I have a workaround, I'll investigate it sometime.

**Comment by paddymcall** [comment]
Please reopen if you trace it down.
