### ISSUE TITLE
Change commas for linebreaks in verse 2, pramanavarttikavrtti.xml

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#30]
One of them eventually leading to an overfull \hbox. Lines 185/186. I guess in xml it would mean to replace the `,` by `</l><l>`? Should I actually make a fork of SARIT-corpus, make the required changes to it and do a pull request?

**Comment by paddymcall** [comment]
Fixed in https://github.com/paddymcall/Stylesheets/commit/caf19b2b15f7ebd874135519df4d8230b391d92c
