### ISSUE TITLE
lb markers at the beginning of every pāda when building without reledmac

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#38]
![selection_105](https://cloud.githubusercontent.com/assets/11517856/15199384/01851266-17de-11e6-97ec-c3a30103051d.png)

Is it a feature or a bug? In case of the former it should be made optional.

**Comment by paddymcall** [comment]
please indicate source of this: revision + filename + linenumber (or xpath)

**Comment by ppasedach** [comment]
https://github.com/ppasedach/SARIT-corpus/blob/8ff956809441cb2d6451af6f794b1a4aa4e7709e/haravijaya.xml , starting at line 82 roughly.  Building the TeX file via `bin/convert_sarit_to_tex_no_ledmac.sh`

**Comment by paddymcall** [comment]
please set the param showLineBreaks=false, that should fix it (it's true per default, so we can see if things go wrong).
