### ISSUE TITLE
keep temporary files in a separate directory

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#39]
Such as .aux and the numbered ones generated by reledmac.

**Comment by paddymcall** [comment]
This would turn make error tracing a bit more difficult (most tools for latex expect things in the same directory).  And it's very easy to remove them: `git clean -i ./TeX/` if you don't need them.  So with `./bin/compile.tex && git clean -i ./TeX/` you'll get what you want.

**Comment by paddymcall** [comment]
Added TeX/.gitignore in https://github.com/paddymcall/SARIT-pdf-conversions/commit/448ad66c7255c16a7c45e2d63567d4212e2b8014 to keep the pdfs around.
