### ISSUE TITLE
pramanavartikavrtti.tex doesn't compile up to end.

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#4]
File compiles only up to p. 319, or l.17431 (17429 in original file, two lines inserted at the beginning cf. Issue #3 ) . fails with `! TeX capacity exceeded, sorry [main memory size=5000000].` This doesn't happen when building the tex file without ledmac. It can be remedied by inserting an empty line before `\begin{center}` .

**Comment by ppasedach** [comment]
[Adding this to the same issue as it seems related:] After adding abovementioned empty line latex hangs again at l. 20032:

```
Section 28 (continuing the previous section) (./pramanavarttikavrtti.28)
! Extra }, or forgotten \endgroup.
\\pend ...f \global \num@lines =\prevgraf \egroup 
                                                  \global \par@line =0\csnum...
<to be read again> 
                   \fi 
\@trivlist ...d \partopsep \else \unskip \par \fi 
                                                  \if@inlabel \@noparitemtru...

\trivlist ... \parskip \@nmbrlistfalse \@trivlist 
                                                  \labelwidth \z@ \leftmargi...

\center ->\trivlist 
                    \centering \item \relax 
l.20032 ^^I  \begin{center}
```

Also this second hanging can be fixed by the insertion of a blank line before `\begin{center}`.

**Comment by paddymcall** [comment]
fixed here: https://github.com/paddymcall/Stylesheets/commit/756ee57172326c974e9fac7a7c681152026b8d7c
