### ISSUE TITLE
Ledmac numbering off?

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#44]
![selection_106](https://cloud.githubusercontent.com/assets/11517856/15651481/3a6d26bc-2680-11e6-9cd3-c58bf89c3bb2.png)

Shouldn't be line 20 the one starting with "cittato"?

(pramanavarttikavrtti p.3)

**Comment by ppasedach** [comment]
![selection_107](https://cloud.githubusercontent.com/assets/11517856/15651651/3f118e1e-2681-11e6-895e-28a5d36ab1bb.png)

Here I would think line 5 should be the one starting with "nanu"?

This happens all over the place.

**Comment by ppasedach** [comment]
Here the corresponding sections with numbering turned on on _every_ line:

![selection_109](https://cloud.githubusercontent.com/assets/11517856/15652091/06b681b6-2684-11e6-880c-0bd62d921765.png)

![selection_108](https://cloud.githubusercontent.com/assets/11517856/15652049/cba40526-2683-11e6-9566-717e040c3369.png)

I suspect that this is a problem of mixing prose with verse, or normal paragraphs with stanzas:
- The last line before of a normal paragraph before any `\stanza` does not receive a number and doesn't increase the counter.
- Wherever we are in a stanza, our line number is increased at `&` and `\&`. Wherever such a line is wrapped, it receives only one number for what appears as two lines in the pdf.
- Some other lines also don't get counted, as the first line after the first quote on p. 2. 

I don't fully understand yet what's happening, but maybe we should consider dropping the use of \stanza for these short quotes? According to my understanding the verse features of ledmac are mostly of interest when wants to be able to address individual lines or paadas in metric text, such as 1a, 1b, 1c, 1d, 2a, 2b, 2c, 2d, which is not what we need here. 

[pramanavarttikavrtti.pdf](https://github.com/paddymcall/SARIT-pdf-conversions/files/289773/pramanavarttikavrtti.pdf)

**Comment by paddymcall** [comment]
> Here I would think line 5 should be the one starting with "nanu"?

Thanks for spotting this, it happens because of the quote environment
around the stanzas, e.g.:

```
%% require snapshot package to record versions to log files
\RequirePackage[log]{snapshot}
\documentclass[article,12pt,a4paper]{memoir}%

%% useful for debugging
%% \usepackage{syntonly}%
%% \syntaxonly%

\usepackage{reledmac}
\setstanzaindents{3,2,2}
\firstlinenum{1}
\linenumincrement{1}

\begin{document}

\begingroup
\beginnumbering

\stanza[\smallbreak]
stanza standard: abc / & def // \&[\smallbreak]



\begin{quote}
  \stanza[\smallbreak]
  stanza in quote: abc / & def // \&[\smallbreak]
\end{quote}

\stanza[\smallbreak]
stanza: abc / & def // \&[\smallbreak]

\endnumbering
\endgroup

\end{document}
```

See Reledmac docs section 16, Quotations: not sure what the expected
behaviour is around/in stanzas.  If you can fix the example above, I can
apply it to the stylesheets.

**Comment by ppasedach** [comment]
So for the moment you've just removed the quote environment around the stanza?

**Comment by paddymcall** [comment]
On Wed, Jun 01 2016, ppasedach wrote:

> So for the moment you've just removed the quote environment around the stanza?

there are now quote marks (`` and ").  alternatives would be to change
font/background, or to have some other indication.  if you have any 
ideas, please let me know.

## 

Patrick McAllister

long-term mail: pma@rdorte.org

**Comment by ppasedach** [comment]
I just looked at the adjustwidth environment. It doesn't have the line numbering problem, but the indentation doesn't work properly. I'm still looking into it.

**Comment by ppasedach** [comment]
I discovered something curious: The file built on my notebook (development version of xetex and a few packages) seems to be doing the numbering correctly:

![selection_113](https://cloud.githubusercontent.com/assets/11517856/15725549/c5c766f0-284c-11e6-9892-e5e0967aacfb.png)

(File created Mon 30 May 2016 01:01:44 PM CEST)

**Comment by ppasedach** [comment]
![selection_114](https://cloud.githubusercontent.com/assets/11517856/15725884/443911e0-284e-11e6-8087-a1e0ec275e2c.png)

The second example from the same version of the file, but note that the line numbers are not reset to zero on the new page. Strange.

**Comment by ppasedach** [comment]
O.k., let's forget about that ghost. I wasn't able to reproduce it this morning. Meanwhile I got [confirmation](http://tex.stackexchange.com/questions/312668/can-one-use-stanza-within-a-quote-environment#comment760950_312668) from Maïeul (maintainer of reledmac) that it's currently not possible to use `\stanza` within a quote environment. He asked me to open a github issue, which I [did](https://github.com/maieul/ledmac/issues/534), however he mentioned that "I won't have time before a lot of time. " 

So your approach was to get rid of the quote environment for now, whereas I think I would prefer to get rid of both quote environment and `\stanza` here and format the passage in a similar fashion as in the following example: 

```
\documentclass[article]{memoir}
\usepackage{reledmac}
\usepackage{lipsum}
\setstanzaindents{3,2,2}
\firstlinenum{1}
\linenumincrement{1}
\begin{document}
\beginnumbering

\pstart
\lipsum[1]
\pend


\pstart
\bigskip
{\large
\noindent\-\hspace{2.5em}verse first line\\ 
\-\hspace{2.5em}verse second line 
}
\pend
\bigskip

\pstart
\lipsum[1]
\pend

\endnumbering

\end{document}
```

![selection_115](https://cloud.githubusercontent.com/assets/11517856/15739813/1b684bfa-28b2-11e6-9f6e-c4f6c5e50a23.png)

**Comment by paddymcall** [comment]
Seems like a good idea.  Could we do this in a single command? I.e., put a newenvironment definition in the preamble and then just call \begin{quoted-verse} xyz \end{quoted-verse}?

**Comment by ppasedach** [comment]
It will not be so easy, as we have to deal with the lines individually, closing all but the last one with `\\`, and prefixing the first one with \noindent. Also it assumes the same indent for all lines, which might be fine, but we could also think of verses in longer meter which you might want to break into four quarters, and then indenting pādas b and d more than a and b. Let me think about it.

**Comment by paddymcall** [comment]
Please reopen issue when we have working environment definition for verses in quotes.
