### ISSUE TITLE
§ not contained in Chandas font

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#45]
The paragraph numbers in gray were supposed to be prefixed by the § character, which doesn't come through as it's not contained in the devanagari font. It could be wrapped such as in `\textenglish{§}`, then it'll show.

**Comment by paddymcall** [comment]
Fixed in https://github.com/paddymcall/Stylesheets/commit/02a9627b085d6d5cf0ff15c02d5fd93a9ab177be
