### ISSUE TITLE
\begingroup \endgroup still necessary?

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#47]
They were required before \beginnumbering and after \endnumbering respectively when the line numbering was generated by reledmac's `\autopar`, but now I think they are not needed anymore.

**Comment by paddymcall** [comment]
removed it, doesn't seem to break much. https://github.com/paddymcall/Stylesheets/commit/19836be18c13b7708e9afa4de78ad843e9de0aa9
