### ISSUE TITLE
TeX Live 2016 is out

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#51]
I guess we want the Readme.org and the .travis.yml files updated accordingly, after some testing?

**Comment by paddymcall** [comment]
Updated the travis build script, please check error output on travis, and suggest fixes:

https://travis-ci.org/paddymcall/SARIT-pdf-conversions/builds

**Comment by paddymcall** [comment]
Closing, as there are no complaints :-)
