### ISSUE TITLE
Test building with development version of gnu freefont 

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#52]
The devanagari range of gnu freefont is taken from the old velthuis devanagari font, but its released version doesn't work well anymore with recent versions of LaTeX using HarfBuzz as font rendering engine, so that it was practically unusable for our purposes. Thus in February I had filed a [bug](https://savannah.gnu.org/bugs/?47294), hoping for an actively maintained open source font. Unfortunately there had been no response to that bug report for a long time, now however I did get a response and was provided with a snapshot of the development version of it, so that I'll do some testing with it. Let's see. It could become a very good font option.

**Comment by ppasedach** [comment]
[pramanavarttikavrtti_freefont.pdf](https://github.com/paddymcall/SARIT-pdf-conversions/files/333554/pramanavarttikavrtti_freefont.pdf) seems to look good.

(Updated after specific loading of the bold font.)

**Comment by paddymcall** [comment]
Please reopen when this font is easily available (or at least the bug at https://savannah.gnu.org/bugs/?47294 is fixed).
