### ISSUE TITLE
Headers miss diacritica

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#53]
![selection_064](https://cloud.githubusercontent.com/assets/11517856/16369423/31966404-3c38-11e6-9c69-d8d2b7e17632.png)

which can be fixed

![selection_065](https://cloud.githubusercontent.com/assets/11517856/16369529/bba117d4-3c38-11e6-8d3d-d53a991fe511.png)

by 

```
           \makeoddhead{ruled}{{\textenglish{Pramāṇavārttika}}}{}{          \textenglish{Dharmakīrti and Manorathanandin}}
```

**Comment by ppasedach** [comment]
I didn't find the string `and Manorathanandin` in the xml file, which makes me believe that the header is generated from the `<titleStmt>`, maybe one needs to add xml:lang="en" in some places there? And probably one would want to change the whole header anyway?

**Comment by paddymcall** [comment]
Fixed in https://github.com/paddymcall/Stylesheets/commit/4fb80c7621603541941c224db12d1471dda82126.
