### ISSUE TITLE
linenumbering around labels

### ISSUE THREAD

**Issue by paddymcall** [paddymcall/SARIT-pdf-conversions#8]
There are labes with attribute type="head" in the document. It seems the reledmac linenumbering brakes around them.  What exactly is the problem in the latex file?

**Comment by ppasedach** [comment]
It is connected to \autopar. See the example below. If you want to get rid of it anyway, it will solve this one, too.

```
\documentclass{memoir}
\usepackage{lipsum,reledmac}
\firstlinenum{1} \linenumincrement{1}

\begin{document}
\beginnumbering
%\autopar
\pstart % Comment out this line for testing \autopar.


\lipsum[1]

\begin{center}
something
\end{center}

\lipsum[2]
\pend % Comment out this line for testing \autopar.
\endnumbering
\end{document}
```
